[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_comai = "Eue9ME4k3iZdLY3a3CpC1vmPsTik1m3Tbx3GsyQ9qamz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
