[features]
seeds = false
skip-lint = false
[programs.localnet]
marketprogram = "Ach3gA8LyvqD6YBxH5bSWZCxP45PaWtzPX8G2fYeYFbb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
